version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - "./app/:/app"

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy:/etc/caddy"
    depends_on:
      - app
