version: "3.8"

services:
  db:
    image: postgres:latest
    env_file: ./app/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: app/.env
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - "./app/:/app"
    depends_on:
      - db

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy:/etc/caddy"
    depends_on:
      - app
